- name: Configure BIND9 DNS Server
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install BIND9
      apt:
        name: bind9
        state: present