---
- name: Install and configure FTP server (vsftpd)
  hosts: ftp_anonymous
  become: yes
  tasks:
    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
        update_cache: yes

    - name: Enable vsftpd service
      systemd:
        name: vsftpd
        enabled: yes
        state: started

    - name: Create shared directory for FTP
      file:
        path: /var/ftp/pub
        state: directory
        mode: '0755'
        owner: ftp
        group: ftp

    - name: Configure vsftpd for anonymous connections
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#anonymous_enable=YES'
        line: 'anonymous_enable=YES'

    - name: Disable local users access in vsftpd
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#local_enable=YES'
        line: 'local_enable=NO'

    - name: Disable write permissions for anonymous users
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#anon_upload_enable=YES'
        line: 'anon_upload_enable=NO'

    - name: Disable mkdir permissions for anonymous users
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#anon_mkdir_write_enable=YES'
        line: 'anon_mkdir_write_enable=NO'

    - name: Set data connection timeout to 30 seconds
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#data_connection_timeout=120'
        line: 'data_connection_timeout=30'

    - name: Set max transfer rate to 5KB/s for anonymous users
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#anon_max_rate=0'
        line: 'anon_max_rate=5120'

    - name: Set FTP banner message
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#ftpd_banner='
        line: 'ftpd_banner=Welcome to SRI FTP anonymous server'

    - name: Create ASCII art file
      copy:
        content: --WELCOME--
        dest: /var/ftp/pub/welcome.txt
        mode: '0644'

    - name: Restart vsftpd service
      systemd:
        name: vsftpd
        state: restarted

- name: Test FTP client modes and verify configurations
  hosts: localhost
  become: no
  tasks:
    - name: Test passive mode FTP connection
      command: "ftp -p 192.168.56.11"
      register: passive_mode_test

    - name: Test active mode FTP connection
      command: "ftp 192.168.56.11"
      register: active_mode_test

    - name: Verify anonymous login works without password
      assert:
        that:
          - passive_mode_test.stdout | search('Login successful')
          - active_mode_test.stdout | search('Login successful')

    - name: Verify directory permissions are read-only for anonymous users
      command: "ls -ld /var/ftp/pub"
      register: dir_permissions

    - name: Verify transfer speeds
      command: "ftp 192.168.56.11 -n -v"
      register: transfer_speeds

    - name: Verify timeout occurs after 30 seconds of inactivity
      command: "ftp 192.168.56.11"
      register: timeout_test